/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aquapluspos.ui;

/**
 *
 * @author geass
 */
public class Pro_Cat_Mana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pro_Cat_Mana.class.getName());

    /**
     * Creates new form test
     */
    public Pro_Cat_Mana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ItemHolder = new javax.swing.JPanel();
        PreSediment = new javax.swing.JButton();
        InlineSedimentFilter = new javax.swing.JButton();
        InlineCarbonFilter = new javax.swing.JButton();
        ROFilter = new javax.swing.JButton();
        AlkalineCartridge = new javax.swing.JButton();
        UFRFilter = new javax.swing.JButton();
        DisHolder = new javax.swing.JPanel();
        Dis = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        ADD = new javax.swing.JButton();
        RepHolder = new javax.swing.JPanel();
        TextScroller = new javax.swing.JScrollPane();
        RepoIn = new javax.swing.JTextArea();
        Report = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setAutoscrolls(true);

        ItemHolder.setBackground(new java.awt.Color(51, 51, 51));
        ItemHolder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PreSediment.setText("Pre Sediment");
        PreSediment.setPreferredSize(new java.awt.Dimension(76, 22));
        PreSediment.addActionListener(this::PreSedimentActionPerformed);

        InlineSedimentFilter.setText("Inline Sediment Filter");
        InlineSedimentFilter.setPreferredSize(new java.awt.Dimension(76, 22));
        InlineSedimentFilter.addActionListener(this::InlineSedimentFilterActionPerformed);

        InlineCarbonFilter.setText("Inline Carbon Filter");
        InlineCarbonFilter.setPreferredSize(new java.awt.Dimension(76, 22));
        InlineCarbonFilter.addActionListener(this::InlineCarbonFilterActionPerformed);

        ROFilter.setText("RO Filter");
        ROFilter.setPreferredSize(new java.awt.Dimension(76, 22));
        ROFilter.addActionListener(this::ROFilterActionPerformed);

        AlkalineCartridge.setText("Alkaline Cartridge");
        AlkalineCartridge.setPreferredSize(new java.awt.Dimension(76, 22));
        AlkalineCartridge.addActionListener(this::AlkalineCartridgeActionPerformed);

        UFRFilter.setText("UFR Filter");
        UFRFilter.setPreferredSize(new java.awt.Dimension(76, 22));
        UFRFilter.addActionListener(this::UFRFilterActionPerformed);

        javax.swing.GroupLayout ItemHolderLayout = new javax.swing.GroupLayout(ItemHolder);
        ItemHolder.setLayout(ItemHolderLayout);
        ItemHolderLayout.setHorizontalGroup(
            ItemHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ItemHolderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ItemHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PreSediment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InlineSedimentFilter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InlineCarbonFilter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ROFilter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlkalineCartridge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UFRFilter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ItemHolderLayout.setVerticalGroup(
            ItemHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ItemHolderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PreSediment, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(InlineSedimentFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(InlineCarbonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ROFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(AlkalineCartridge, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(UFRFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        DisHolder.setBackground(new java.awt.Color(51, 51, 51));
        DisHolder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout DisLayout = new javax.swing.GroupLayout(Dis);
        Dis.setLayout(DisLayout);
        DisLayout.setHorizontalGroup(
            DisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DisLayout.setVerticalGroup(
            DisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        Update.setText("Update");

        Delete.setText("Delete");

        ADD.setText("Add & Insert more data");

        javax.swing.GroupLayout DisHolderLayout = new javax.swing.GroupLayout(DisHolder);
        DisHolder.setLayout(DisHolderLayout);
        DisHolderLayout.setHorizontalGroup(
            DisHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisHolderLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(DisHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ADD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DisHolderLayout.createSequentialGroup()
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        DisHolderLayout.setVerticalGroup(
            DisHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisHolderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Dis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DisHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        RepHolder.setBackground(new java.awt.Color(51, 51, 51));
        RepHolder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        RepoIn.setColumns(20);
        RepoIn.setRows(5);
        TextScroller.setViewportView(RepoIn);

        Report.setText("Report");

        javax.swing.GroupLayout RepHolderLayout = new javax.swing.GroupLayout(RepHolder);
        RepHolder.setLayout(RepHolderLayout);
        RepHolderLayout.setHorizontalGroup(
            RepHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RepHolderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RepHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Report, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextScroller, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addContainerGap())
        );
        RepHolderLayout.setVerticalGroup(
            RepHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RepHolderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(TextScroller, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Report, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ItemHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DisHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RepHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DisHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RepHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ItemHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PreSedimentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreSedimentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreSedimentActionPerformed

    private void InlineSedimentFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InlineSedimentFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InlineSedimentFilterActionPerformed

    private void InlineCarbonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InlineCarbonFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InlineCarbonFilterActionPerformed

    private void ROFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ROFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ROFilterActionPerformed

    private void AlkalineCartridgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlkalineCartridgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlkalineCartridgeActionPerformed

    private void UFRFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UFRFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UFRFilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pro_Cat_Mana().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton AlkalineCartridge;
    private javax.swing.JButton Delete;
    private javax.swing.JPanel Dis;
    private javax.swing.JPanel DisHolder;
    private javax.swing.JButton InlineCarbonFilter;
    private javax.swing.JButton InlineSedimentFilter;
    private javax.swing.JPanel ItemHolder;
    private javax.swing.JButton PreSediment;
    private javax.swing.JButton ROFilter;
    private javax.swing.JPanel RepHolder;
    private javax.swing.JTextArea RepoIn;
    private javax.swing.JButton Report;
    private javax.swing.JScrollPane TextScroller;
    private javax.swing.JButton UFRFilter;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
